substitutions:
  _REGION: 'us-east1'
  _REPOSITORY: 'docker-repo'
  _IMAGE: 'nginx-app'
  _TAG: 'v1.02'
  _LOG_BUCKET: 'devops_ci_logs'

steps:
# 1. Build and Push using Kaniko with Reproducible flag
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-and-push'
  args:
    - --context=dir://app
    - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
    - --cache=true
    - --cache-ttl=168h
    - --reproducible=true  # <--- CRITICAL: Strips timestamps to keep SHA-256 consistent

# 2. List all images in the repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'list-all-images'
  args:
  - 'artifacts'
  - 'docker'
  - 'images'
  - 'list'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}'


# 3. Inspect the image to verify RootFS layers (Focusing on the layers list)
- name: 'gcr.io/cloud-builders/docker'
  id: 'inspect-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
      echo "--- ROOTFS LAYERS ---"
      docker inspect --format='{{json .RootFS.Layers}}' ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}

# 4. Run functional tests
- name: 'gcr.io/cloud-builders/docker'
  id: 'test-image'
  args: ['run', '--rm', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}', 'echo', 'Tests passed']

logsBucket: 'gs://${_LOG_BUCKET}'